resize_shape: [256, 256]
targets: ['Fire_Images']
model_file_paths: ["fire_cnn_classifier_params.h5", "fire_cnn_classifier_layers.json"]
base_model_url: "https://github.com/JosephCottingham/Fire_Detection_Project/releases/tag/V1.0.0"
model_sha256: "dd1efc4b1ce188efa5f9bf558f513d3c75a3198e"
